# -*- coding: utf-8 -*-
"""W1D5DC1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1loQjGwjfdppQYjuduR4-o8l7vAPG4aXQ
"""

class Circle:
  def __init__(self, radius):
    self.radius = radius

  def get_area(self):
    return 3.14 * self.radius ** 2

  def __str__(self):
    return f"Circle with radius: {self.radius}"

  def __add__(self,other):
    new_radius=self.radius+other.radius
    return Circle(new_radius)

  def __gt__(self,other):
    return self.radius>other.radius

  def __eq__(self,other):
    return self.radius==other.radius

  def __dir__(self):
    return self.radius


circle = Circle(5)
circlebis = Circle(10)
circle.__add__(circlebis).__str__()
circle.__gt__(circlebis)
circle.__eq__(circlebis)